/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GeoEngineNode {
  constructor(options?: EngineOptionsJs | undefined | null);
  /**
   * Register a named zone from a GeoJSON Polygon object.
   * Optionally provide dwell thresholds to debounce enter/exit events.
   */
  registerZone(
    id: string,
    polygon: any,
    dwell?: DwellOptionsJs | undefined | null,
  ): void;
  /** Register a named catalog region from a GeoJSON Polygon object. */
  registerCatalogRegion(id: string, polygon: any): void;
  /**
   * Register a named circle by center point and radius (same units as coordinates).
   * Optionally provide dwell thresholds to debounce approach/recede events.
   */
  registerCircle(
    id: string,
    cx: number,
    cy: number,
    r: number,
    dwell?: DwellOptionsJs | undefined | null,
  ): void;
  /** Define a configurable rule. Fires a `rule` event when triggers and filters match. */
  defineRule(config: RuleConfigJs): void;
  /** Define a sequence rule. Fires `sequence_complete` when all steps match in order. */
  defineSequence(config: SequenceConfigJs): void;
  /** Return the current state snapshot for an entity, or undefined if not yet seen. */
  getEntityState(id: string): EntityStateJs | null;
  /** Return state snapshots for all known entities. */
  getEntities(): Array<EntityStateJs>;
  /** Return all entities whose logical zone membership includes `zone_id`. */
  entitiesInZone(zoneId: string): Array<EntityStateJs>;
  /** Return all entities whose logical circle membership includes `circle_id`. */
  entitiesInCircle(circleId: string): Array<EntityStateJs>;
  /** Return all entities whose current catalog region matches `region_id`. */
  entitiesInRegion(regionId: string): Array<EntityStateJs>;
  /** Return all entities within `radius` of `(x, y)`, sorted by distance ascending. */
  entitiesNearPoint(
    x: number,
    y: number,
    radius: number,
  ): Array<EntityWithDistanceJs>;
  /** Return the `k` nearest entities to `(x, y)`, sorted by distance ascending. */
  nearestToPoint(x: number, y: number, k: number): Array<EntityWithDistanceJs>;
  /**
   * Process a batch of point updates and return the resulting events.
   * Updates are sorted by entity ID then timestamp before processing.
   */
  ingest(updates: Array<PointUpdateJs>): Array<any>;
}

export interface DwellOptionsJs {
  minInsideMs?: number;
  minOutsideMs?: number;
}

export interface EngineOptionsJs {
  /** Maximum historical position samples per entity. Default: 10. */
  historySize?: number;
}

/** Snapshot of current entity state returned from getEntityState / getEntities. */
export interface EntityStateJs {
  id: string;
  x: number;
  y: number;
  tMs: number;
  speed?: number;
  heading?: number;
}

/** Entity state plus Euclidean distance from a query point, returned from spatial queries. */
export interface EntityWithDistanceJs {
  id: string;
  x: number;
  y: number;
  tMs: number;
  speed?: number;
  heading?: number;
  /** Euclidean distance from the query point in the same units as coordinates. */
  distance: number;
}

export interface PointUpdateJs {
  id: string;
  x: number;
  y: number;
  /** Unix epoch milliseconds. i64 maps to TS `number` (u64 would map to BigInt). */
  tMs: number;
}

/** Configuration for a user-defined rule. */
export interface RuleConfigJs {
  name: string;
  triggers: Array<RuleTriggerJs>;
  filters: Array<RuleFilterJs>;
  /** Name of the emitted `rule` event. */
  emit: string;
  /** Arbitrary JSON payload attached to every emitted event. */
  data?: any;
}

/** A single filter condition for a configurable rule. */
export interface RuleFilterJs {
  /** One of: "speed_above", "speed_below", "heading_between". */
  filterType: string;
  /** Speed threshold in units/s (used for speed_above / speed_below). */
  value?: number;
  /** Start of heading range in degrees (used for heading_between). */
  from?: number;
  /** End of heading range in degrees (used for heading_between). */
  to?: number;
}

/** A single trigger condition for a configurable rule. */
export interface RuleTriggerJs {
  /** One of: "enter", "exit", "approach", "recede". */
  eventKind: string;
  /** The zone or circle id to watch. */
  targetId: string;
}

/** Configuration for a sequence rule. */
export interface SequenceConfigJs {
  name: string;
  /** Zone/circle ids that must be triggered (enter/approach) in order. */
  steps: Array<string>;
  /** Optional window in ms; sequence resets if not completed within this time. */
  withinMs?: number;
}
