/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GeoEngineNode {
  constructor();
  /**
   * Register a named zone from a GeoJSON Polygon object.
   * Optionally provide dwell thresholds to debounce enter/exit events.
   */
  registerZone(
    id: string,
    polygon: any,
    dwell?: DwellOptionsJs | undefined | null,
  ): void;
  /** Register a named catalog region from a GeoJSON Polygon object. */
  registerCatalogRegion(id: string, polygon: any): void;
  /** Register a named circle by center point and radius (same units as coordinates). */
  registerCircle(id: string, cx: number, cy: number, r: number): void;
  /**
   * Process a batch of point updates and return the resulting events.
   * Updates are sorted by entity ID then timestamp before processing.
   */
  ingest(updates: Array<PointUpdateJs>): Array<any>;
}

export interface DwellOptionsJs {
  minInsideMs?: number;
  minOutsideMs?: number;
}

export interface PointUpdateJs {
  id: string;
  x: number;
  y: number;
  /** Unix epoch milliseconds. i64 maps to TS `number` (u64 would map to BigInt). */
  tMs: number;
}
