/**
 * Typed overlay for the NAPI-RS native bindings.
 *
 * The auto-generated `index.d.ts` types `ingest()` as `unknown[]` because the
 * Rust side returns `Vec<serde_json::Value>`. This file provides:
 *   - `GeoEvent` — a discriminated union for all 7 event variants
 *   - `GeoEngine` — a typed wrapper around the native `GeoEngineNode` class
 *
 * Import from this file rather than directly from `index.js` for full type safety.
 */

// Re-export input types under cleaner names.
// These are generated by NAPI-RS from the #[napi(object)] structs in lib.rs.
export type { PointUpdateJs as PointUpdate, DwellOptionsJs as DwellOptions } from './index.js'

// ---------------------------------------------------------------------------
// Event discriminated union
// ---------------------------------------------------------------------------

export type GeoEvent =
  | { kind: 'enter';              id: string; zone: string;          t_ms: number }
  | { kind: 'exit';               id: string; zone: string;          t_ms: number }
  | { kind: 'approach';           id: string; circle: string;        t_ms: number }
  | { kind: 'recede';             id: string; circle: string;        t_ms: number }
  /** `region` is `null` when the entity left all catalog regions (unassigned). */
  | { kind: 'assignment_changed'; id: string; region: string | null; t_ms: number }

// ---------------------------------------------------------------------------
// Typed GeoEngine wrapper
// ---------------------------------------------------------------------------

import { GeoEngineNode, type PointUpdateJs, type DwellOptionsJs } from './index.js'

export class GeoEngine {
  private node: GeoEngineNode

  constructor() {
    this.node = new GeoEngineNode()
  }

  registerZone(id: string, polygon: object, dwell?: DwellOptionsJs): void {
    this.node.registerZone(id, polygon, dwell ?? null)
  }

  registerCatalogRegion(id: string, polygon: object): void {
    this.node.registerCatalogRegion(id, polygon)
  }

  registerCircle(id: string, cx: number, cy: number, r: number): void {
    this.node.registerCircle(id, cx, cy, r)
  }

  ingest(updates: PointUpdateJs[]): GeoEvent[] {
    return this.node.ingest(updates) as GeoEvent[]
  }
}
